### PR TITLE
Fix parsing chapter & verse out of books that start with a number

### PR DESCRIPTION
**Pull request by kobsy**
Before, the normalized reference being generated for "1 John 1" was "11" instead of "1", since it wasn't stripping out the initial "1", but it _was_ stripping out "John".

### CODE REVIEW

**Review by boblail — CHANGES_REQUESTED** [review]
This should be backed up with a test.

I don't think this change is right. `REFERENCE_NORMALIZATIONS` should be applied to the reference part of a pericope (e.g. **12:1-8** in **Exodus 12:1–8**). Stripping leading digits would remove the chapter!

**Comment by kobsy** [comment]
When I dropped a `debugger` in there, the whole reference was being passed in, so **Exodus 12:1-8** instead of just **12:1-8**. Hence, the proposed fix. But you're definitely right that we should have a test for this. I'll add one.

**Comment by boblail** [comment]
> When I dropped a debugger in there, the whole reference was being passed in, so **Exodus 12:1-8** instead of just **12:1-8**.

Ah! That's the bug! `normalizeReference` is called by [`parseReference`](https://github.com/boblail/pericope.js/blob/master/src/pericope.coffee#L92) which expects the book name and reference part of a pericope to have been split already.

The bug must be [here](https://github.com/boblail/pericope.js/blob/master/src/pericope.coffee#L83). 

For reference, [here's the Ruby implementation of this method](https://github.com/boblail/pericope/blob/master/lib/pericope.rb#L360-L362).

In both cases, `PERICOPE_PATTERN` has a capture group for each book of the Bible and then a 67th capture group for the reference part of a pericope. (I think there's a 68th capture group for the whole thing too...)

In Ruby, `MatchData` acts as an array with 68 slots and we find the book slot that isn't `nil` and grab the reference from the last slot.

`RegExp#exec` doesn't work the same way in Javascript, so the implementation isn't identical. I think the bug must be in the Javascript implementation of `matchAll`.

**Comment by kobsy** [comment]
Turns out the problem was not in Pericope, but how we were using it. We were trying to pass in the whole reference to `parseReference`, which was causing the issue. I'll close the PR.

**Pull request closed without merging**
